{% set version = "1.1.13" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-decoder
  version: {{ version|replace("-", "_") }}

source:
  fn: decoder_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/decoder_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/decoder/decoder_{{ version }}.tar.gz
  sha256: e6d5bddbd64ba539b0599be621785f1c68917286415dea8047d9c946cae9ecce

build:
  noarch: generic
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-backports
  run:
    - r-base
    - r-backports

test:
  commands:
    - $R -e "library('decoder')"           # [not win]
    - "\"%R%\" -e \"library('decoder')\""  # [win]

about:
  home: https://www.bitbucket.com/cancercentrum/decoder
  license: GPL-2
  summary: Main function "decode" is used to decode coded key values to plain text. Function
    "code" can be used to code plain text to code if there is a 1:1 relation between
    the two. The concept relies on 'keyvalue' objects used for translation. There are
    several 'keyvalue' objects included in the areas of geographical regional codes,
    administrative health care unit codes, diagnosis codes and more. It is also easy
    to extend the use by arbitrary  code sets.
  license_family: GPL2
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
    - dbast
