appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: QN1JeKI/JO4foU2wibtMY3U+NaEC1Ng+yku1eB6t2Bdxy/S6psiFjCseD2bXAxW0/M7vltPWwsfYHj3ZvfAr1cAT+dsAMkSfeqXe8fBhaRwZLWoYsKpHuv46bEnLRYqdZMs7Ck7zPIxUR/oFyXlMYFPw5FTRzi3EzEXARTqHN9Vi0owiNMsa7ICJ66MNjtnSENeO5B6UDsvza0E9EeQM2hziU7HipOBy+71QSXstGKrOc6t0F4BUlzwh92zDvI5ZX4bnLOGcGHjWEOO2oiyoxzdf9hdXJ/RVXgPYM6nAWU4N7XN0h8i9J/FX9bHv0u3G39r1vw+TncW0J9fFUm+9HFojo0r2XgwMmEI/58XA6mCRWsl1gnbnXCyy47WKZvHfNY7MFjnpSApyjj0jo/7Zpd5Wt3QKjfWjEjO+f0Tr/67OO7cARVvcHafHBVj39QZ4v1f3sEx8oCV6p4ZVTAEsIvBw1hA+vhH6WGvefcJyX1HayNc6U131fQDaUJJdenHoO3qV89Z1V95mXBdfk9KMdNanKq4glTFaoDDpIbWsYE5zWBM5xuCAQ9S9pUP/PTl1uaYEJKUo4zGDiRp9J+V9AAZGdFzzdsWgg0aroDeqM7XqMC6kXqNUrtNhDQ0qLmkUFaVmQ6KVYZQI4pAP3rvlm+enuA94i+TvCoMBX7EV5h0=}
bot:
  automerge: true
